INSERT INTO FINALIDADE(descricao) VALUES('Vender'),('Alugar');

INSERT INTO PARAMETRO(chave,valor) VALUES('email', 'contato@focoimovel.com.br');

INSERT INTO estado (nome,sigla) VALUES ('Acre','AC'),
('Alagoas','AL'),
('Amapá','AP'),
 ('Amazonas','AM'),
 ('Bahia','BA'),
 ('Ceará','CE'),
 ('Distrito Federal','DF'),
 ('Espírito Santo','ES'),
 ('Goiás','GO'),
 ('Maranhão','MA'),
 ('Mato Grosso','MT'),
 ('Mato Grosso do Sul','MS'),
 ('Minas Gerais','MG'),
 ('Pará','PA'),
 ('Paraíba','PB'),
 ('Paraná','PR'),
 ('Pernambuco','PE'),
 ('Piauí','PI'),
 ('Rio de Janeiro','RJ'),
 ('Rio Grande do Norte','RN'),
 ('Rio Grande do Sul','RS'),
 ('Rondônia','RO'),
 ('Roraima','RR'),
 ('Santa Catarina','SC'),
 ('São Paulo','SP'),
 ('Sergipe','SE'),
 ('Tocantins','TO');

INSERT INTO cidade (nome,id_estado) VALUES ('São Bernardo do Campo',25),
('Santo André',25),
('São Caetano do Sul',25),
('Osasco', 25),
('Carapicuiba',25);

INSERT INTO diferenciais (descricao) VALUES  ('Academia'),
 ('Aquecimento'),
 ('Ar Condicionado'),
 ('Área de Serviço'),
 ('Churrasqueira'),
 ('Cozinha'),
 ('Depósito'),
 ('Elevador'),
 ('Escritório'),
 ('Espaço Gourmet'),
 ('Espaço Verde / Parque'),
 ('Garagem'),
 ('Gramado'),
 ('Jardim'),
 ('Lareira'),
 ('Lavanderia'),
 ('Mobiliado'),
 ('Piscina'),
 ('Playground'),
 ('Quadra Poliesportiva'),
 ('Quintal'),
 ('Sacada'),
 ('Salão de Festas'),
 ('Sauna'),
 ('TV a Cabo'),
 ('Varanda Gourmet');

